import smtplib

my_email = "threshold686@gmail.com"
# password generated by google for app permissions
my_password = "yifbdobttrghvnfl"
# setup connection
connection = smtplib.SMTP("smtp.gmail.com")
# enable encryption
connection.starttls()
# login
connection.login(user=my_email, password=my_password)
# sending email from sender to recipient with message
connection.sendmail(from_addr=my_email, to_addrs="threshold247@gmail.com", msg="Testing")
# close connection
connection.close()
