import smtplib
import datetime as dt
import random


my_email = "threshold686@gmail.com"
# password generated by google for app permissions
my_password = "yifbdobttrghvnfl"
# access date and time class
now = dt.datetime.now()

# only accessing the week day
week_day = now.weekday()
print(week_day)
if week_day == 4:
    # open txt file, convert to list and generate random quote
    with open("quotes.txt") as file:
        # return list of all quotes
        quotes = file.readlines()
        # get a random quote from the list
        random_quote = random.choice(quotes)
    print(random_quote)
    # setup connection
    with smtplib.SMTP("smtp.gmail.com") as connection:
        # enable encryption
        connection.starttls()
        # login
        connection.login(user=my_email, password=my_password)
        # sending email from sender to recipient with message
        connection.sendmail(from_addr=my_email,
                            to_addrs="threshold247@gmail.com",
                            msg=f"Subject:Random Quote\n\n {random_quote}")

# # access year from date time class
# year = now.year
# # access date from date time class
# date = now.date()
# print(year, date)
