import time
import requests
from datetime import datetime
import smtplib as smtp

# My co-ordinates
MY_LAT = -33.927109
MY_LONG = 18.420059
my_email = "threshold686@gmail.com"
# password generated by google for app permissions
my_password = "yifbdobttrghvnfl"


# function to check for iss satellite position and to compare user co-ordinates to satellite co-ordinates.
def compare_pos():
    response = requests.get(url="http://api.open-notify.org/iss-now.json")
    response.raise_for_status()
    # create JSON
    iss_data = response.json()

    longitude = float(iss_data["iss_position"]["longitude"])
    latitude = float(iss_data["iss_position"]["latitude"])
# check if iss position is within user position by 5 degrees
    if MY_LAT + 5 <= latitude or MY_LAT - 5 <= latitude and MY_LONG + 5 <= longitude or MY_LONG - 5 <= longitude:
        return True


def is_night():
    parameters = {
        "lat": MY_LAT,
        "lng": MY_LONG,
        "formatted": 0
    }

    response = requests.get(url="https://api.sunrise-sunset.org/json", params=parameters)
    response.raise_for_status()
    # create JSON
    data = response.json()
    # get sunrise time (hour) adjusted to timezone
    sunrise = int(data["results"]["sunrise"].split("T")[1].split(":")[0])+2
    # get sunset time (hour) adjusted to timezone
    sunset = int(data["results"]["sunset"].split("T")[1].split(":")[0])+2
    # get time now (hour)
    time_now = datetime.now().hour
    # check to see if it is still dark.
    if time_now <= sunrise or time_now >= sunset:
        return True

# runs a loop to check
while True:
    # checks every 4 mins
    time.sleep(240)
    # if conditions are True
    if compare_pos() and is_night():
        with smtp.SMTP("smtp.gmail.com") as connection:
            # enable encryption
            connection.starttls()
            # login
            connection.login(user=my_email, password=my_password)
            # sending email from sender to recipient with message
            connection.sendmail(from_addr=my_email,
                                to_addrs=my_email,
                                msg=f"Subject:Iss Position\n\n Look up")


